version: '3'
services:

  # dns 서버
  dns_server:
    hostname: dns_server
    restart: always
    container_name: dns_server
    build:
      context: ./dns_server
      dockerfile: Dockerfile
    volumes:
      - ./dns_server/db:/etc/bind/mydb
    networks:
      default_bridge:
        ipv4_address: 172.18.0.2
    
    

  # 메일서버
  nn_server:
    hostname: mail.nn.com
    container_name: nn_server
    build:
      context: ./nn_server
      dockerfile: Dockerfile
    networks:
      default_bridge:
        ipv4_address: 172.18.0.4

  gg_server:
    hostname: mail.gg.com
    container_name: gg_server
    build:
      context: ./gg_server
      dockerfile: Dockerfile
    networks:
      default_bridge:
        ipv4_address: 172.18.0.5

  # 클라이언트
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      default_bridge:
        ipv4_address: 172.18.0.3

networks: 
  default_bridge: 
    enable_ipv6: false
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16

